# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.0.0
      - image: postgres:11.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: parkdude-test
          POSTGRES_PASSWORD: password

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/      

    working_directory: ~/parkdude-backend

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run: mv env/app.test.example.env env/app.test.env && mv env/app.sam-dev.example.env env/app.sam-dev.env      
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}      
      
      - run: npm test
      - run: npm run lint
